name: ephphotography.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16514
title: EPH Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed0f79'
    - '#000000'
    - '#9b8f97'
    - '#555555'
    - '#ffffff'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
